// app/layout.js or wherever your RootLayout is
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import { Anton } from "next/font/google";

import Footer from "@/footer";
import Navbar from "@/Navbar";
import "./globals.css";

// Load fonts with CSS variable support
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppins.variable} 
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${anton.variable}
          antialiased
        `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
